version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./www/html:/var/www/html
            - ./logs:/var/log/nginx
        links:
            - php
            - mysql
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www/html:/var/www/html
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: 'mysql'
            MYSQL_PASSWORD: 'secret'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8080:80"
            - "8443:443"
        links:
            - mysql
        environment:
            PHPMYADMIN_PASSWORD: secret
            PMA_HOST: mysql